language: csharp
solution: L20n.sln
mono:
  - latest
  - 3.10.0
  - 3.8.0
install:
  - nuget restore L20n.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release L20n.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./tests/L20n.Tests/bin/Release/L20n.Tests.dll
